services:
  postgres:
    image: postgres:latest
    container_name: naruto-postgres
    environment:
      POSTGRES_DB: api_naruto
      POSTGRES_USER: audrey
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: